### ISSUE TITLE
undefined reference to 'call_UMFPACK'

### ISSUE THREAD

**Issue by laods** [OPM/opm-core#208]
With the newest commits of opm-core (branch release 2013/.03), I was faced with the following building error:

[ 93%] Building CXX object CMakeFiles/test_geom2d.dir/tests/test_geom2d.cpp.o
lib/libopmcore.a(TransportSolverTwophaseImplicit.cpp.o): In function 'void   Opm::ImplicitTransportLinAlgSupport::CSRMatrixUmfpackSolver::solve<std::vector<double, std::allocator<double> > >(CSRMatrix const&, std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> >&)':
/private/laods/opm/RH5/realization_cmake/pure_cmake/src/opm-core/opm  /core/transport/implicit/CSRMatrixUmfpackSolver.hpp:61: undefined reference to   `call_UMFPACK'

Can this error have been introduced in PR #203? At least opm-core@e59db97128 builds fine.
