### ISSUE TITLE
PETSc support does not compile on Debian wheezy with g++4.4

### ISSUE THREAD

**Issue by blattms** [OPM/opm-core#726]
I did the mistake and made a clean build which detected PetSc (version 3.2) on my system. Unfortunately, the PETSc supports seems broken due to my local version and compiler:

```sh
[  2%] Building CXX object CMakeFiles/opmcore.dir/opm/core/linalg/LinearSolverPetsc.cpp.o
/usr/bin/g++-4.4   -DHAVE_CONFIG_H=1 -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -g -O0 -Wall -Wextra -pipe -Wno-unknown-pragmas -std=c++0x -DNDEBUG -mtune=native -I/home/mblatt/src/dune/opm/opm-core/opm-parallel -I/home/mblatt/src/dune/opm/opm-core -I/usr/include/suitesparse -I/usr/include/superlu -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -I/usr/include/petsc -I/home/mblatt/src/dune/3rdParty/ert/include -I/home/mblatt/src/dune/opm/dune-common -I/home/mblatt/src/dune/opm/dune-istl -I/home/mblatt/src/dune/opm/opm-parser    -o CMakeFiles/opmcore.dir/opm/core/linalg/LinearSolverPetsc.cpp.o -c /home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp: In constructor ‘Opm::<unnamed>::KSPTypeMap::KSPTypeMap(const std::string&)’:
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:41: error: ‘KSPCHEBYSHEV’ was not declared in this scope
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp: At global scope:
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:178: warning: unused parameter ‘nonzeros’
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp: In member function ‘virtual Opm::LinearSolverInterface::LinearSolverReport Opm::LinearSolverPetsc::solve(int, int, const int*, const int*, const double*, const double*, double*, const boost::any&) const’:
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:262: warning: missing initializer for member ‘Opm::LinearSolverInterface::LinearSolverReport::converged’
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:262: warning: missing initializer for member ‘Opm::LinearSolverInterface::LinearSolverReport::iterations’
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:262: warning: missing initializer for member ‘Opm::LinearSolverInterface::LinearSolverReport::residual_reduction’
In file included from /usr/include/c++/4.4/bits/stl_algobase.h:66,
                 from /usr/include/c++/4.4/algorithm:61,
                 from /usr/include/boost/any.hpp:13,
                 from /home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverInterface.hpp:23,
                 from /home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.hpp:23,
                 from /home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:23:
/usr/include/c++/4.4/bits/stl_pair.h: In constructor ‘std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&) [with _U1 = const char*, _U2 = const char*, _T1 = const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _T2 = char*]’:
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:40:   instantiated from here
/usr/include/c++/4.4/bits/stl_pair.h:107: error: invalid conversion from ‘const char*’ to ‘char*’
make[2]: *** [CMakeFiles/opmcore.dir/opm/core/linalg/LinearSolverPetsc.cpp.o] Fehler 1
make[2]: Leaving directory `/home/mblatt/src/dune/opm-amg-opt/opm-core/opm-parallel'
make[1]: *** [CMakeFiles/opmcore.dir/all] Fehler 2
make[1]: Leaving directory `/home/mblatt/src/dune/opm-amg-opt/opm-core/opm-parallel'
make: *** [all] Fehler 2
```

**Comment by andlaus** [comment]
@blattms what's the status of this? it seems to be some peculiarity that only occurs with with self-compiled PETSc libraries, right?

**Comment by blattms** [comment]
This is stock Debian wheezy package. The problem still persists. BTW It is not due to the Petsc version or cmake, but due to non g++4-4 compliant programming in LinearSolverPetsc

**Comment by blattms** [comment]
There is now even an additional problem (which ist PETSc version related):

```sh
[  0%] Building CXX object CMakeFiles/opmcore.dir/opm/core/linalg/LinearSolverPetsc.cpp.o
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp: In constructor ‘Opm::<unnamed>::KSPTypeMap::KSPTypeMap(const std::string&)’:
/home/mblatt/src/dune/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:41: error: ‘KSPCHEBYSHEV’ was not declared in this scope
```

**Comment by blattms** [comment]
The original problem is the missing conversion from const char* (argument to make_pair) to std::string (key of the unordered_map).

**Comment by atgeirr** [comment]
The original problem should be easy to solve by using the convenience [] syntax. Original:
```
type_map_.insert(std::make_pair("richardson", KSPRICHARDSON));
```
Suggested replacement:
```
type_map_["richardson"] = KSPRICHARDSON;
```

The problem of KSPCHEBYSHEV not being available I have no solution for, but one simple solution (if it is so that it is only available in some versions of PETSc) is to just delete that line. It will then no be available at all, but that is necessary until we have some "if petsc version is greater than..." mechanism to use.

Can you try those fixes @blattms, and if successful: make a PR of it? I will then make it part of the release. I am reluctant to implement the suggested fixes myself since I am on a different platform/compiler and do not have PETSc installed (so I could make a basic mistake and not notice).

**Comment by bska** [comment]
> type_map_.insert(std::make_pair("richardson", KSPRICHARDSON));

It's even easier to use a typedef
```C++
typedef Map::value_type VT;

// ...
type_map_.insert(VT("richardson", KSPRICHARDSON));
// ...
```

**Comment by blattms** [comment]
I am on it.

**Comment by blattms** [comment]
@bard Sorry, that does not work and raises the same error. I guess the
problem is indeed in constructing the pair with a const char*.

**Comment by bard** [comment]
@blattms please double-check the results of nick autocompletion. :)

**Comment by bska** [comment]
@blattms 
> Sorry, that [using a `typedef` for the `map::value_type`] does not work and raises the same error

I'm slightly surprised.  The example below builds and runs as expected when I target CentOS 5.11 with GCC 4.4:
```sh
$ g++44 -Wall -Wextra -std=c++0x -pedantic -O2 t.cpp && ./a.out
u:
  [three] = 3
  [two] = 2
  [one] = 1
m:
  [one] = 1
  [three] = 3
  [two] = 2
```

Example follows
```C++
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <unordered_map>

namespace {
    std::unordered_map<std::string, int>
    umap()
    {
        typedef std::unordered_map<std::string, int> M;
        typedef M::value_type VT; 

        M m;
        m.insert(VT("one", 1));
        m.insert(VT("two", 2));
        m.insert(VT("three", 3));

        return m;
    }

    std::map<std::string, int>
    map()
    {
        typedef std::map<std::string, int> M;
        typedef M::value_type VT; 

        M m;
        m.insert(VT("one", 1));
        m.insert(VT("two", 2));
        m.insert(VT("three", 3));

        return m;
    }
}

int main()
try {
    auto u = umap();
    auto m = map();

    std::cout << "u:\n";
    for (auto b = u.begin(), e = u.end(); b != e; ++b) {
        std::cout << "  [" << b->first << "] = " << b->second << '\n';
    }

    std::cout << "m:\n";
    for (auto b = m.begin(), e = m.end(); b != e; ++b) {
        std::cout << "  [" << b->first << "] = " << b->second << '\n';
    }
}
catch (std::exception& e) {
    std::cout << "e.what() = " << e.what() << '\n';
}
```

**Comment by blattms** [comment]
@bska
> @blattms 
> > Sorry, that [using a `typedef` for the `map::value_type`] does not work and raises the same error
> 
> [working sample code]

Indeed, your code compiles fine. But it seems like the PCType used in
PETSc, which is the entry in the unordered map, is something like
char*. But I am not 100% sure as the code is rather cryptic to me:

```
#define KSPType character*(80)
#define KSPRICHARDSON 'richardson'
```

According to the error message this is equivalent to
```
#define PCType char*
#define KSPRICHARDSON 'richardson'
```

Changing your example along the lines of this triggers an error in
```
...
    umap()
    {
        typedef std::unordered_map<std::string, PCType> M;
        typedef M::value_type VT;

        M m;
        m.insert(VT("one", KSPRICHARDSON)); // converting const char* to char*

        return m;
    }
...
```

**Comment by bska** [comment]
@blattms 
> Indeed, your code compiles fine. But it seems like the `PCType` used in PETSc, which is the entry in the unordered map, is something like `char*`.

Aha, I didn't think of that possibility--I was sure it was the key that was causing the problem, not the value.  I had implicitly assumed that the `PCType` was some kind of `enum`.  If it rather is some kind of pointer to `char` I'm not at all surprised things go belly up.  In that case using `operator[]()` is clearly superior to any contortionist statment involving `.insert()`.
